import {ApolloClient, InMemoryCache, gql } from '@apollo/client'
import Head from 'next/head'
import { useState } from 'react'
import Event from "../components/Events"
import styles from '../styles/Home.module.css'

export default function Home(results) {
  const initialState = results
  const [events, setEvents] = useState(initialState.events)
  console.log(initialState)
  return (
    <div className={styles.container}>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Event events={events}/>
      
    </div>
  )
}

export async function getStaticProps(){
  const client = new ApolloClient({
    uri: "https://dev.peddlesoft.com/graphql",
    cache: new InMemoryCache(),
  });

  const {data} = await client.query({
    query: gql`
     query{
        events {
          id
          theme
          description
          venue
          code
          startDate
          startTime
          endDate
          endTime
        }
      }`,
  })

  return{
    props:{
      events: data.events
    }
  }
}